export const elements = {
  loginText: document.getElementById('login-btn'),
  editionDisplayElements: document.querySelectorAll('.display-login'),
  editionFilterBar: document.querySelector('.filter'),
  galleryDisplay: document.querySelector('.gallery'),
  filterContainer: document.querySelector('.filter'),
  boutonLogin: document.getElementById('login-btn'),
  boutonModify: document.querySelector('.modify-btn'),
  modal: document.getElementById('modal'),
  modalMain: document.querySelector('.modal-content-main'),
  modalAdd: document.querySelector('.modal-content-add'),
  modalGallery: document.querySelector('.modal-gallery'),
  addNewWorkBtn: document.getElementById('add-work'),
  returnArrow: document.querySelector('.return-arrow'),
  formUpload: document.getElementById('form-upload'),
  validateBtn: document.getElementById('validate-work'),
  addImgBtn: document.querySelector('.add-image-btn'),
  fileImg: document.querySelector('.file-img'),
  fileInput: document.getElementById('file'),
  workName: document.getElementById('work-name'),
  categoryName: document.getElementById('select-cat'),
  formContact: document.getElementById('form-contact')
}
